INSERT INTO Nacionalidade (Nome) VALUES
('Argentina'),
('Portugal'),
('Croácia'),
('França'),
('Brasil'),
('Itália'),
('Alemanha'),
('Inglaterra'),
('Espanha'),
('Tchéquia'),
('Rússia'),
('Escócia'),
('Hungria'),
('Países Baixos'),
('Ucrânia'),
('Dinamarca'),
('Bulgária'),
('Libéria');

INSERT INTO Posicao (Nome) VALUES
('Goleiro'),
('Zagueiro'),
('Lateral'),
('Volante'),
('Meia'),
('Atacante');

INSERT INTO Jogador (Nome, NacionalidadeId, PosicaoId, Altura, Imagem, Descricao) VALUES
('Stanley Matthews', 8, 6, 1.72, '\\img\\jogadores\\stanley_matthews.jpg', 'Lenda inglesa do futebol, conhecido como o "Feiticeiro do Drible", primeiro vencedor da Bola de Ouro em 1956.'),
('Alfredo Di Stéfano', 1, 6, 1.76, '\\img\\jogadores\\alfredo_di_stefano.jpg', 'Argentino naturalizado espanhol, símbolo do Real Madrid e bicampeão da Bola de Ouro.'),
('Raymond Kopa', 4, 5, 1.68, '\\img\\jogadores\\raymond_kopa.jpg', 'Craque francês que brilhou no Stade de Reims e no Real Madrid, campeão europeu nos anos 50.'),
('Luis Suárez Miramontes', 9, 5, 1.75, '\\img\\jogadores\\luis_suarez_1960.jpg', 'Espanhol cerebral, destaque no Barcelona e Inter de Milão, vencedor da Bola de Ouro em 1960.'),
('Omar Sivori', 1, 6, 1.68, '\\img\\jogadores\\omar_sivori.jpg', 'Atacante argentino de enorme técnica, ídolo da Juventus e Napoli, campeão em 1961.'),
('Josef Masopust', 10, 5, 1.77, '\\img\\jogadores\\josef_masopust.jpg', 'Tcheco elegante e líder em campo, levou a Tchecoslováquia ao vice mundial e venceu a Bola de Ouro em 1962.'),
('Lev Yashin', 11, 1, 1.89, '\\img\\jogadores\\lev_yashin.jpg', 'O lendário "Aranha Negra", único goleiro a vencer a Bola de Ouro, símbolo do Dínamo Moscou e da URSS.'),
('Denis Law', 12, 6, 1.75, '\\img\\jogadores\\denis_law.jpg', 'Escocês artilheiro do Manchester United, ídolo dos anos 60 e campeão da Bola de Ouro em 1964.'),
('Eusébio', 2, 6, 1.75, '\\img\\jogadores\\eusebio.jpg', 'O "Pantera Negra", símbolo do Benfica e maior jogador da história de Portugal, campeão em 1965.'),
('Bobby Charlton', 8, 5, 1.73, '\\img\\jogadores\\bobby_charlton.jpg', 'Ídolo do Manchester United e campeão mundial em 1966, meia de técnica e liderança.'),
('Flórián Albert', 13, 6, 1.82, '\\img\\jogadores\\florian_albert.jpg', 'Atacante húngaro de grande talento, ídolo do Ferencváros e vencedor da Bola de Ouro em 1967.'),
('George Best', 8, 6, 1.75, '\\img\\jogadores\\george_best.jpg', 'Gênio e ídolo do Manchester United, conhecido por seu estilo e talento, campeão da Bola de Ouro em 1968.'),
('Gianni Rivera', 6, 5, 1.75, '\\img\\jogadores\\gianni_rivera.jpg', 'Meia italiano clássico do Milan, cérebro da equipe e vencedor em 1969.'),
('Gerd Müller', 7, 6, 1.76, '\\img\\jogadores\\gerd_muller.jpg', 'O “Bombardeiro da Baviera”, um dos maiores artilheiros da história, campeão da Bola de Ouro em 1970.'),
('Johan Cruijff', 14, 6, 1.78, '\\img\\jogadores\\johan_cruijff.jpg', 'Símbolo do futebol total holandês, tricampeão da Bola de Ouro (1971, 1973, 1974).'),
('Franz Beckenbauer', 7, 2, 1.81, '\\img\\jogadores\\franz_beckenbauer.jpg', 'O “Kaiser”, defensor e líder da Alemanha e do Bayern, bicampeão da Bola de Ouro.'),
('Oleg Blokhin', 15, 6, 1.79, '\\img\\jogadores\\oleg_blokhin.jpg', 'Atacante ucraniano ídolo do Dínamo Kiev, campeão da Bola de Ouro em 1975.'),
('Allan Simonsen', 16, 6, 1.65, '\\img\\jogadores\\allan_simonsen.jpg', 'Dinamarquês ágil e técnico, destaque do Borussia Mönchengladbach, vencedor em 1977.'),
('Kevin Keegan', 8, 6, 1.73, '\\img\\jogadores\\kevin_keegan.jpg', 'Atacante inglês e ídolo do Liverpool e Hamburgo, bicampeão da Bola de Ouro (1978, 1979).'),
('Karl-Heinz Rummenigge', 7, 6, 1.82, '\\img\\jogadores\\rummenigge.jpg', 'Atacante alemão do Bayern de Munique, bicampeão da Bola de Ouro (1980, 1981).'),
('Paolo Rossi', 6, 6, 1.74, '\\img\\jogadores\\paolo_rossi.jpg', 'Herói da Itália na Copa de 1982, artilheiro e vencedor da Bola de Ouro no mesmo ano.'),
('Michel Platini', 4, 5, 1.78, '\\img\\jogadores\\michel_platini.jpg', 'Craque francês tricampeão da Bola de Ouro, ídolo da Juventus e da seleção francesa.'),
('Igor Belanov', 15, 6, 1.75, '\\img\\jogadores\\igor_belanov.jpg', 'Atacante ucraniano do Dínamo Kiev, vencedor da Bola de Ouro em 1986.'),
('Ruud Gullit', 14, 5, 1.91, '\\img\\jogadores\\ruud_gullit.jpg', 'Líder holandês e estrela do Milan dos anos 80, campeão da Bola de Ouro em 1987.'),
('Marco van Basten', 14, 6, 1.88, '\\img\\jogadores\\marco_van_basten.jpg', 'Atacante elegante e letal do Milan e da Holanda, tricampeão da Bola de Ouro (1988, 1989, 1992).'),
('Lothar Matthäus', 7, 5, 1.74, '\\img\\jogadores\\lothar_matthaus.jpg', 'Meia alemão campeão mundial em 1990, símbolo de liderança e força, vencedor da Bola de Ouro.'),
('Jean-Pierre Papin', 4, 6, 1.76, '\\img\\jogadores\\jean_pierre_papin.jpg', 'Artilheiro francês do Olympique de Marseille, campeão da Bola de Ouro em 1991.'),
('Roberto Baggio', 6, 5, 1.74, '\\img\\jogadores\\roberto_baggio.jpg', 'Craque italiano de técnica e genialidade, ídolo da Juventus e vencedor em 1993.'),
('Hristo Stoichkov', 17, 6, 1.78, '\\img\\jogadores\\hristo_stoichkov.jpg', 'Atacante búlgaro explosivo, estrela do Barcelona e campeão da Bola de Ouro em 1994.'),
('George Weah', 18, 6, 1.84, '\\img\\jogadores\\george_weah.jpg', 'Liberiano e ídolo do Milan, primeiro africano a vencer a Bola de Ouro (1995).'),
('Mathias Sammer', 7, 2, 1.81, '\\img\\jogadores\\mathias_sammer.jpg', 'Zagueiro líbero alemão, destaque do Borussia Dortmund e campeão em 1996.'),
('Ronaldo', 5, 6, 1.83, '\\img\\jogadores\\ronaldo.jpg', 'O Fenômeno. Brilhou no Barcelona, Inter e Real Madrid, bicampeão da Bola de Ouro.'),
('Zinedine Zidane', 4, 5, 1.85, '\\img\\jogadores\\zinedine_zidane.jpg', 'Craque francês do Juventus e Real Madrid, vencedor da Bola de Ouro de 1998.'),
('Rivaldo', 5, 5, 1.86, '\\img\\jogadores\\rivaldo.jpg', 'Meia-atacante brasileiro, destaque no Barcelona e campeão da Bola de Ouro em 1999.'),
('Luís Figo', 2, 5, 1.80, '\\img\\jogadores\\luis_figo.jpg', 'Português clássico e técnico, ídolo do Barcelona e Real Madrid, campeão da Bola de Ouro em 2000.'),
('Michael Owen', 8, 6, 1.73, '\\img\\jogadores\\michael_owen.jpg', 'Atacante inglês veloz e letal do Liverpool, campeão da Bola de Ouro em 2001.'),
('Pavel Nedved', 10, 5, 1.77, '\\img\\jogadores\\pavel_nedved.jpg', 'Craque tcheco da Juventus, reconhecido por sua garra e técnica, campeão da Bola de Ouro em 2003.'),
('Andriy Shevchenko', 15, 6, 1.83, '\\img\\jogadores\\andriy_shevchenko.jpg', 'Ídolo ucraniano do Milan e artilheiro da Europa, campeão da Bola de Ouro em 2004.'),
('Ronaldinho Gaúcho', 5, 5, 1.82, '\\img\\jogadores\\ronaldinho.jpg', 'Símbolo da alegria no futebol, encantou o mundo no Barcelona, campeão da Bola de Ouro em 2005.'),
('Fabio Cannavaro', 6, 2, 1.76, '\\img\\jogadores\\fabio_cannavaro.jpg', 'Zagueiro italiano e capitão da seleção campeã do mundo em 2006, vencedor da Bola de Ouro.'),
('Kaká', 5, 5, 1.86, '\\img\\jogadores\\kaka.jpg', 'Meia elegante e técnico, destaque do Milan e vencedor da Bola de Ouro de 2007.'),
('Cristiano Ronaldo', 2, 6, 1.87, '\\img\\jogadores\\cristiano_ronaldo.jpg', 'Lenda portuguesa, cinco vezes vencedor da Bola de Ouro, ídolo de Manchester United, Real Madrid e Portugal.'),
('Lionel Messi', 1, 6, 1.70, '\\img\\jogadores\\lionel_messi.jpg', 'Argentino e maior vencedor da história da Bola de Ouro, símbolo do Barcelona e campeão mundial de 2022.'),
('Luka Modric', 3, 5, 1.72, '\\img\\jogadores\\luka_modric.jpg', 'Craque croata e cérebro do meio-campo do Real Madrid, vencedor da Bola de Ouro de 2018.'),
('Karim Benzema', 4, 6, 1.85, '\\img\\jogadores\\karim_benzema.jpg', 'Atacante francês de técnica refinada, ídolo do Real Madrid, campeão da Bola de Ouro em 2022.'),
('Rodri', 9, 4, 1.91, '\\img\\jogadores\\rodri.jpg', 'Volante espanhol do Manchester City, destaque mundial e vencedor da Bola de Ouro 2024.'),
('Ousmane Dembélé', 4, 6, 1.78, '\\img\\jogadores\\ousmane_dembele.jpg', 'Atacante francês veloz e habilidoso, campeão da Bola de Ouro em 2025.');

INSERT INTO Premio (Nome, Ano, JogadorId) VALUES
('Bola de Ouro', 1956, 1),
('Bola de Ouro', 1957, 2),
('Bola de Ouro', 1958, 3),
('Bola de Ouro', 1959, 2),
('Bola de Ouro', 1960, 4),
('Bola de Ouro', 1961, 5),
('Bola de Ouro', 1963, 6),
('Bola de Ouro', 1965, 7),
('Bola de Ouro', 1971, 8),
('Bola de Ouro', 1972, 9),
('Bola de Ouro', 1973, 8),
('Bola de Ouro', 1974, 8),
('Bola de Ouro', 1976, 9),
('Bola de Ouro', 1983, 10),
('Bola de Ouro', 1984, 10),
('Bola de Ouro', 1985, 10),
('Bola de Ouro', 1988, 11),
('Bola de Ouro', 1989, 11),
('Bola de Ouro', 1992, 11),
('Bola de Ouro', 1997, 12),
('Bola de Ouro', 2002, 12),
('Bola de Ouro', 2005, 13),
('Bola de Ouro', 2007, 14),
('Bola de Ouro', 2008, 15),
('Bola de Ouro', 2013, 15),
('Bola de Ouro', 2014, 15),
('Bola de Ouro', 2016, 15),
('Bola de Ouro', 2017, 15),
('Bola de Ouro', 2009, 16),
('Bola de Ouro', 2010, 16),
('Bola de Ouro', 2011, 16),
('Bola de Ouro', 2012, 16),
('Bola de Ouro', 2015, 16),
('Bola de Ouro', 2019, 16),
('Bola de Ouro', 2021, 16),
('Bola de Ouro', 2023, 16),
('Bola de Ouro', 2018, 17),
('Bola de Ouro', 2022, 18),
('Bola de Ouro', 2024, 19),
('Bola de Ouro', 2025, 20);

INSERT INTO Clube (Nome, Imagem) VALUES
('Real Madrid', '\\img\\clubes\\real_madrid.jpg'),
('Barcelona', '\\img\\clubes\\barcelona.jpg'),
('Manchester United', '\\img\\clubes\\manchester_united.jpg'),
('Liverpool', '\\img\\clubes\\liverpool.jpg'),
('Juventus', '\\img\\clubes\\juventus.jpg'),
('AC Milan', '\\img\\clubes\\ac_milan.jpg'),
('Inter de Milão', '\\img\\clubes\\inter_milan.jpg'),
('Bayern de Munique', '\\img\\clubes\\bayern_munich.jpg'),
('Borussia Dortmund', '\\img\\clubes\\borussia_dortmund.jpg'),
('Borussia Mönchengladbach', '\\img\\clubes\\borussia_monchengladbach.jpg'),
('Ajax', '\\img\\clubes\\ajax.jpg'),
('Benfica', '\\img\\clubes\\benfica.jpg'),
('Chelsea', '\\img\\clubes\\chelsea.jpg'),
('Manchester City', '\\img\\clubes\\manchester_city.jpg'),
('Paris Saint-Germain', '\\img\\clubes\\psg.jpg'),
('Napoli', '\\img\\clubes\\napoli.jpg'),
('Hamburgo', '\\img\\clubes\\hamburgo.jpg'),
('Ferencváros', '\\img\\clubes\\ferencvaros.jpg'),
('Dínamo Kiev', '\\img\\clubes\\dinamo_kiev.jpg'),
('Dínamo Moscou', '\\img\\clubes\\dinamo_moscou.jpg'),
('Stade de Reims', '\\img\\clubes\\stade_reims.jpg'),
('Fiorentina', '\\img\\clubes\\fiorentina.jpg'),
('Arsenal', '\\img\\clubes\\arsenal.jpg'),
('Tottenham', '\\img\\clubes\\tottenham.jpg'),
('Leeds United', '\\img\\clubes\\leeds_united.jpg'),
('Atlético de Madrid', '\\img\\clubes\\atletico_madrid.jpg'),
('Valencia', '\\img\\clubes\\valencia.jpg'),
('Porto', '\\img\\clubes\\porto.jpg'),
('Sporting CP', '\\img\\clubes\\sporting_cp.jpg'),
('Rangers', '\\img\\clubes\\rangers.jpg'),
('Celtic', '\\img\\clubes\\celtic.jpg'),
('Dínamo Zagreb', '\\img\\clubes\\dinamo_zagreb.jpg'),
('CSKA Moscou', '\\img\\clubes\\cska_moscou.jpg'),
('Anderlecht', '\\img\\clubes\\anderlecht.jpg'),
('Sevilla', '\\img\\clubes\\sevilla.jpg'),
('Villarreal', '\\img\\clubes\\villarreal.jpg'),
('Shakhtar Donetsk', '\\img\\clubes\\shakhtar_donetsk.jpg'),
('Everton', '\\img\\clubes\\everton.jpg'),
('West Ham', '\\img\\clubes\\west_ham.jpg'),
('Newcastle United', '\\img\\clubes\\newcastle_united.jpg');
